// packages/solid/src/context.ts
import type { IconContextValue } from "@mal-icons/core";
import { createContext } from "solid-js";
import type { JSX } from "solid-js";

/** Theming context value for all mal-icons Solid components. */
export type SolidIconContextValue = IconContextValue<JSX.CSSProperties>;

/** Default (empty) theming configuration. */
export const DefaultIconContext: SolidIconContextValue = {};

/**
 * Solid context carrying icon theming (size, color, className, style).
 * Consumed via `useContext` inside {@link IconBase}; provide values with
 * `<IconContext.Provider value={…}>`.
 */
export const IconContext = createContext<SolidIconContextValue>(DefaultIconContext);

// packages/react-native/src/context.ts
import type { IconContextValue } from "@mal-icons/core";
import { createContext } from "react";
import type { StyleProp, ViewStyle } from "react-native";

/** Theming context value for all mal-icons React Native components. */
export type ReactNativeIconContextValue = IconContextValue<StyleProp<ViewStyle>>;

/** Default (empty) theming configuration. */
export const DefaultIconContext: ReactNativeIconContextValue = {};

/**
 * React context carrying icon theming (size, color, style). Consumed via
 * `useContext` inside {@link IconBase} — never `Consumer`.
 */
export const IconContext = createContext<ReactNativeIconContextValue>(DefaultIconContext);
