// examples/react/src/App.tsx
import {
  ICON_ANIMATIONS_CSS,
  type IconAnimation,
  IconContext,
  type IconWeight,
  type ReactIconContextValue,
} from "@mal-icons/react";
import { FiCheck, FiCopy, FiGithub, FiSearch } from "@mal-icons/react/fi";
import { useMemo, useState } from "react";
import { ICONS } from "./icons.ts";

const WEIGHTS: IconWeight[] = ["thin", "light", "regular", "bold"];
const ANIMATIONS: Array<IconAnimation | "none"> = [
  "none",
  "spin",
  "spin-reverse",
  "pulse",
  "beat",
  "bounce",
  "ping",
  "shake",
  "wiggle",
  "float",
  "heartbeat",
  "flip",
  "rotate",
  "zoom",
  "fade",
  "slide",
  "glow",
  "swing",
  "tada",
];

export function App() {
  const [size, setSize] = useState(32);
  const [color, setColor] = useState("#6366f1");
  const [weight, setWeight] = useState<IconWeight>("regular");
  const [animate, setAnimate] = useState<IconAnimation | "none">("none");
  const [query, setQuery] = useState("");
  const [copied, setCopied] = useState<string | null>(null);

  const filtered = useMemo(() => {
    const q = query.trim().toLowerCase();
    if (!q) return ICONS;
    return ICONS.filter(([name]) => name.toLowerCase().includes(q));
  }, [query]);

  // `size` and `color` are theming-context fields; `weight` is a per-icon prop.
  const contextValue = useMemo<ReactIconContextValue>(() => ({ size, color }), [size, color]);

  async function copyImport(name: string) {
    await navigator.clipboard?.writeText(`import { ${name} } from "@mal-icons/react/fi";`);
    setCopied(name);
    window.setTimeout(() => setCopied((c) => (c === name ? null : c)), 1200);
  }

  return (
    <IconContext.Provider value={contextValue}>
      {/* Animations are pure CSS; inject the keyframes once. */}
      <style>{ICON_ANIMATIONS_CSS}</style>

      <div className="page">
        <header className="hero">
          <div className="hero__badge">React 19 · Vite</div>
          <h1 className="hero__title">
            mal-icons <span>for React</span>
          </h1>
          <p className="hero__subtitle">
            Tree-shakeable, ahead-of-time generated icons with a single, consistent API. Theme
            everything through context and override per-icon.
          </p>
          <a
            className="hero__link"
            href="https://github.com/MAnasLatif/mal-icons"
            target="_blank"
            rel="noreferrer"
          >
            <FiGithub size={18} /> View on GitHub
          </a>
        </header>

        <section className="panel" aria-label="Icon controls">
          <label className="field field--search">
            <FiSearch size={18} className="field__icon" />
            <input
              type="search"
              placeholder="Search icons…"
              value={query}
              onChange={(e) => setQuery(e.target.value)}
            />
          </label>

          <label className="field">
            <span>Size · {size}px</span>
            <input
              type="range"
              min={16}
              max={64}
              value={size}
              onChange={(e) => setSize(Number(e.target.value))}
            />
          </label>

          <label className="field">
            <span>Color</span>
            <input type="color" value={color} onChange={(e) => setColor(e.target.value)} />
          </label>

          <label className="field">
            <span>Weight</span>
            <select value={weight} onChange={(e) => setWeight(e.target.value as IconWeight)}>
              {WEIGHTS.map((w) => (
                <option key={w} value={w}>
                  {w}
                </option>
              ))}
            </select>
          </label>

          <label className="field">
            <span>Animation</span>
            <select
              value={animate}
              onChange={(e) => setAnimate(e.target.value as IconAnimation | "none")}
            >
              {ANIMATIONS.map((a) => (
                <option key={a} value={a}>
                  {a}
                </option>
              ))}
            </select>
          </label>
        </section>

        <main className="grid" aria-label="Icon gallery">
          {filtered.map(([name, Icon]) => (
            <button
              key={name}
              type="button"
              className="card"
              title={`Copy import for ${name}`}
              onClick={() => copyImport(name)}
            >
              <span className="card__icon">
                <Icon
                  weight={weight}
                  animate={animate === "none" ? undefined : animate}
                  title={name}
                />
              </span>
              <span className="card__name">{name}</span>
              <span className="card__copy">
                {copied === name ? (
                  <>
                    <FiCheck size={14} /> Copied
                  </>
                ) : (
                  <>
                    <FiCopy size={14} /> Copy
                  </>
                )}
              </span>
            </button>
          ))}

          {filtered.length === 0 && <p className="empty">No icons match “{query}”.</p>}
        </main>

        <footer className="footer">
          Showing {filtered.length} of {ICONS.length} curated Feather icons. The full set ships 287
          tree-shakeable modules.
        </footer>
      </div>
    </IconContext.Provider>
  );
}

// examples/angular/src/app/app.component.ts
import { NgComponentOutlet } from "@angular/common";
import { Component, computed, signal } from "@angular/core";
import { ICON_ANIMATIONS_CSS, type IconAnimation, animationClass } from "@mal-icons/angular";
import { FiCheck, FiCopy, FiGithub, FiSearch, ICONS } from "./icons";

const ANIMATIONS: Array<IconAnimation | "none"> = [
  "none",
  "spin",
  "spin-reverse",
  "pulse",
  "beat",
  "bounce",
  "ping",
  "shake",
  "wiggle",
  "float",
  "heartbeat",
  "flip",
  "rotate",
  "zoom",
  "fade",
  "slide",
  "glow",
  "swing",
  "tada",
];

@Component({
  selector: "app-root",
  standalone: true,
  imports: [NgComponentOutlet, FiGithub, FiSearch, FiCopy, FiCheck],
  template: `
    <div class="page">
      <header class="hero">
        <div class="hero__badge">Angular 22 · Vite</div>
        <h1 class="hero__title">mal-icons <span>for Angular</span></h1>
        <p class="hero__subtitle">
          Tree-shakeable, ahead-of-time generated standalone components. Each icon builds a
          native &lt;svg&gt; with Renderer2 — no innerHTML, no runtime string parsing.
        </p>
        <a
          class="hero__link"
          href="https://github.com/MAnasLatif/mal-icons"
          target="_blank"
          rel="noreferrer"
        >
          <mal-fi-github [size]="18" /> View on GitHub
        </a>
      </header>

      <section class="panel" aria-label="Icon controls">
        <label class="field field--search">
          <mal-fi-search [size]="18" className="field__icon" />
          <input
            type="search"
            placeholder="Search icons…"
            [value]="query()"
            (input)="query.set($any($event.target).value)"
          />
        </label>

        <label class="field">
          <span>Size · {{ size() }}px</span>
          <input
            type="range"
            min="16"
            max="64"
            [value]="size()"
            (input)="size.set(+$any($event.target).value)"
          />
        </label>

        <label class="field">
          <span>Color</span>
          <input
            type="color"
            [value]="color()"
            (input)="color.set($any($event.target).value)"
          />
        </label>

        <label class="field">
          <span>Animation</span>
          <select [value]="animate()" (change)="animate.set($any($event.target).value)">
            @for (a of animations; track a) {
              <option [value]="a">{{ a }}</option>
            }
          </select>
        </label>
      </section>

      <main class="grid" aria-label="Icon gallery">
        @for (entry of filtered(); track entry[0]) {
          <button
            type="button"
            class="card"
            [title]="'Copy import for ' + entry[0]"
            (click)="copyImport(entry[0])"
          >
            <span class="card__icon">
              <ng-container
                *ngComponentOutlet="entry[1]; inputs: inputsFor(entry[0])"
              ></ng-container>
            </span>
            <span class="card__name">{{ entry[0] }}</span>
            <span class="card__copy">
              @if (copied() === entry[0]) {
                <mal-fi-check [size]="14" /> Copied
              } @else {
                <mal-fi-copy [size]="14" /> Copy
              }
            </span>
          </button>
        }

        @if (filtered().length === 0) {
          <p class="empty">No icons match “{{ query() }}”.</p>
        }
      </main>

      <footer class="footer">
        Showing {{ filtered().length }} of {{ total }} curated Feather icons. The full set ships
        287 tree-shakeable standalone components.
      </footer>
    </div>
  `,
})
export class AppComponent {
  readonly animations = ANIMATIONS;
  readonly total = ICONS.length;

  readonly size = signal(32);
  readonly color = signal("#6366f1");
  readonly animate = signal<IconAnimation | "none">("none");
  readonly query = signal("");
  readonly copied = signal<string | null>(null);

  readonly filtered = computed(() => {
    const q = this.query().trim().toLowerCase();
    if (!q) return ICONS;
    return ICONS.filter(([name]) => name.toLowerCase().includes(q));
  });

  constructor() {
    // Animations are pure CSS; inject the keyframes once.
    const style = document.createElement("style");
    style.textContent = ICON_ANIMATIONS_CSS;
    document.head.appendChild(style);
  }

  /** Build the `@Input` bag for a gallery icon (props override any context). */
  inputsFor(name: string): Record<string, unknown> {
    const animate = this.animate();
    return {
      size: this.size(),
      color: this.color(),
      title: name,
      className: animate === "none" ? undefined : animationClass(animate),
    };
  }

  async copyImport(name: string): Promise<void> {
    await navigator.clipboard?.writeText(`import { ${name} } from "@mal-icons/angular/fi";`);
    this.copied.set(name);
    window.setTimeout(() => {
      if (this.copied() === name) this.copied.set(null);
    }, 1200);
  }
}
