// packages/solid/src/context.ts
import type { IconContextValue } from "@mal-icons/core";
import { createContext } from "solid-js";
import type { JSX } from "solid-js";

/** Theming context value for all mal-icons Solid components. */
export type SolidIconContextValue = IconContextValue<JSX.CSSProperties>;

/** Default (empty) theming configuration. */
export const DefaultIconContext: SolidIconContextValue = {};

/**
 * Solid context carrying icon theming (size, color, className, style).
 * Consumed via `useContext` inside {@link IconBase}; provide values with
 * `<IconContext.Provider value={…}>`.
 */
export const IconContext = createContext<SolidIconContextValue>(DefaultIconContext);

// packages/angular/src/context.ts
import { InjectionToken } from "@angular/core";
import type { IconContextValue } from "@mal-icons/core";

/** Theming context value for all mal-icons Angular components. */
export type AngularIconContextValue = IconContextValue<Record<string, string>>;

/** Default (empty) theming configuration. */
export const DefaultIconContext: AngularIconContextValue = {};

/**
 * Injection token carrying icon theming (size, color, className, attr).
 * Provide it in a component/module to theme all descendant mal-icons
 * components; consumed inside {@link IconBaseComponent}.
 */
export const ICON_CONTEXT = new InjectionToken<AngularIconContextValue>("mal-icons-context", {
  factory: () => DefaultIconContext,
});
