// packages/react/src/context.ts
import type { IconContextValue } from "@mal-icons/core";
import { createContext } from "react";
import type { CSSProperties } from "react";

/** Theming context for all mal-icons React components. */
export type ReactIconContextValue = IconContextValue<CSSProperties>;

/** Default (empty) theming configuration. */
export const DefaultIconContext: ReactIconContextValue = {};

/**
 * React context carrying icon theming (size, color, className, style).
 * Consumed via `useContext` inside {@link IconBase} — never `Consumer`.
 */
export const IconContext = createContext<ReactIconContextValue>(DefaultIconContext);

// packages/solid/src/context.ts
import type { IconContextValue } from "@mal-icons/core";
import { createContext } from "solid-js";
import type { JSX } from "solid-js";

/** Theming context value for all mal-icons Solid components. */
export type SolidIconContextValue = IconContextValue<JSX.CSSProperties>;

/** Default (empty) theming configuration. */
export const DefaultIconContext: SolidIconContextValue = {};

/**
 * Solid context carrying icon theming (size, color, className, style).
 * Consumed via `useContext` inside {@link IconBase}; provide values with
 * `<IconContext.Provider value={…}>`.
 */
export const IconContext = createContext<SolidIconContextValue>(DefaultIconContext);
